#version: '3.8'

volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/soljeong/data/mariadb
  wordpress-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/soljeong/data/wordpress
services: 
  mariadb:
      image: mariadb
      build: ./requirements/mariadb/.
      restart: always
      expose:
        - "3306"
      networks:
        - intra
      volumes:
        - mariadb-volume:/var/lib/mysql
      tty: true
      env_file:
        - .env
  nginx: 
    image: nginx
    restart : always 
    build : ./requirements/nginx/. 
    ports:
      - "443:443" 
    volumes:
      - wordpress-volume:/var/www/html
    networks:
      - intra 
    tty: true 
  wordpress:
        image: wordpress
        restart: always
        build : ./requirements/wordpress/. 
        volumes:
            - wordpress-volume:/var/www/html
        expose: 
            - "9000"
        networks:
            - intra
        tty: true
        env_file:
          - .env
networks:
  intra : 
    driver: bridge 
