version: '3.8'

volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/soljeong/data/mariadb
  wordpress-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/soljeong/data/wordpress
services: 
  mariadb:
      image: mariadb
      build: ./requirements/mariadb/.
      restart: always
      expose:
        - "3306"
      networks:
        - inception
      volumes:
        - mariadb-volume:/var/lib/mysql
      tty: true
      environment:
          MARIADB_DB : ${MARIADB_DB}
          MARIADB_ID : ${MARIADB_ID}
          MARIADB_PW : ${MARIADB_PW}
          MARIADB_ROOT : ${MARIADB_ROOT}
          MARIADB_HOST : ${MARIADB_HOST}
  nginx: 
    image: nginx
    restart : always 
    build : ./requirements/nginx/. 
    ports:
      - "443:443" 
    volumes:
      - wordpress-volume:/var/www/html
    networks:
      - inception
    tty: true 
  wordpress:
        image: wordpress
        restart: always
        build : ./requirements/wordpress/. 
        volumes:
            - wordpress-volume:/var/www/html
        expose: 
            - "9000"
        networks:
            - inception
        tty: true
        environment:
          MARIADB_DB : ${MARIADB_DB}
          MARIADB_ID : ${MARIADB_ID}
          MARIADB_PW : ${MARIADB_PW}
          MARIADB_ROOT : ${MARIADB_ROOT}
          MARIADB_HOST : ${MARIADB_HOST}
          WP_URL : ${WP_URL}
          WP_TITLE : ${WP_TITLE}
          WP_ADMIN_ID : ${WP_ADMIN_ID}
          WP_ADMIN_PW : ${WP_ADMIN_PW}
          WP_ADMIN_EMAIL : ${WP_ADMIN_EMAIL}
          WP_USER_ID : ${WP_USER_ID}
          WP_USER_PW : ${WP_USER_PW}
          WP_USER_EMAIL : ${WP_USER_EMAIL}
networks:
  inception : 
    driver: bridge 
