FROM debian:bullseye

EXPOSE 443

RUN apt-get update &&\
    apt-get upgrade -y &&\
    apt-get -y install nginx openssl vim dumb-init

COPY ./conf/default.conf /etc/nginx/conf.d/default.conf
COPY ./tools /etc/nginx/tools

RUN mkdir /etc/nginx/ssl
RUN chmod +x /etc/nginx/tools/nginx.sh

ENTRYPOINT ["dumb-init", "--", "/etc/nginx/tools/nginx.sh"]
